/**
 * IndexStore and server argument resolution: error paths over temp
 * directories, plus load caching and change detection over the real fixture.
 *
 * The fixture index is generated by make-fixture.ts (wired as `pretest`);
 * these tests fail loudly when it is absent rather than passing vacuously.
 */

import assert from "node:assert/strict";
import { test } from "node:test";
import { cpSync, existsSync, mkdtempSync, rmSync, utimesSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createIndexStore } from "./store.js";
import { resolveIndexDirFromArgs } from "./server.js";
import { FIXTURE_INDEX_DIR } from "./make-fixture.js";

function requireFixture(): void {
  assert.ok(
    existsSync(join(FIXTURE_INDEX_DIR, "metadata.json")),
    `fixture index missing at ${FIXTURE_INDEX_DIR} - run \`npm run fixture --workspace @repohive/mcp\` (pretest does this automatically)`,
  );
}

test("load fails with a guiding message when the index directory does not exist", () => {
  const store = createIndexStore(join(tmpdir(), "repohive-mcp-definitely-absent-2f9c"));
  const outcome = store.load();
  assert.equal(outcome.ok, false);
  if (!outcome.ok) {
    assert.match(outcome.message, /index directory not found/);
    assert.match(outcome.message, /repository\.json/);
    assert.match(outcome.message, /npm run parse/);
  }
});

test("load reports every missing index file for an empty directory", () => {
  const dir = mkdtempSync(join(tmpdir(), "repohive-mcp-empty-"));
  try {
    const outcome = createIndexStore(dir).load();
    assert.equal(outcome.ok, false);
    if (!outcome.ok) {
      assert.match(outcome.message, /missing index files/);
      for (const name of [
        "repository.json",
        "hierarchy.json",
        "nodes.json",
        "edges.json",
        "metadata.json",
      ]) {
        assert.ok(outcome.message.includes(name), `message should name ${name}`);
      }
    }
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("load names the malformed file when one index member is corrupt", () => {
  requireFixture();
  const dir = mkdtempSync(join(tmpdir(), "repohive-mcp-corrupt-"));
  try {
    cpSync(FIXTURE_INDEX_DIR, dir, { recursive: true });
    writeFileSync(join(dir, "edges.json"), "{ not json", "utf8");
    const outcome = createIndexStore(dir).load();
    assert.equal(outcome.ok, false);
    if (!outcome.ok) {
      assert.match(outcome.message, /malformed index file edges\.json/);
    }
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("load parses the real fixture and caches the view until a file changes", () => {
  requireFixture();
  const dir = mkdtempSync(join(tmpdir(), "repohive-mcp-cache-"));
  try {
    cpSync(FIXTURE_INDEX_DIR, dir, { recursive: true });
    const store = createIndexStore(dir);
    const first = store.load();
    assert.equal(first.ok, true);
    const second = store.load();
    assert.equal(second.ok, true);
    if (first.ok && second.ok) {
      assert.equal(second.view, first.view, "unchanged index must return the cached view object");
      assert.equal(first.view.hierarchy.repositoryId.startsWith("r_"), true);
    }

    // A changed mtime invalidates the cache; the reloaded view is a new
    // object over identical data.
    const later = new Date(Date.now() + 5_000);
    utimesSync(join(dir, "metadata.json"), later, later);
    const third = store.load();
    assert.equal(third.ok, true);
    if (first.ok && third.ok) {
      assert.notEqual(third.view, first.view, "changed file must invalidate the cached view");
      assert.equal(third.view.metadata.nodeCount, first.view.metadata.nodeCount);
    }
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("resolveIndexDirFromArgs accepts --index, a positional, or the environment", () => {
  const cwd = "/work/project";

  const flag = resolveIndexDirFromArgs(["--index", "out/index"], {}, cwd);
  assert.deepEqual(flag, { ok: true, indexDir: "/work/project/out/index" });

  const positional = resolveIndexDirFromArgs(["/abs/index"], {}, cwd);
  assert.deepEqual(positional, { ok: true, indexDir: "/abs/index" });

  const env = resolveIndexDirFromArgs([], { REPOHIVE_INDEX: "elsewhere" }, cwd);
  assert.deepEqual(env, { ok: true, indexDir: "/work/project/elsewhere" });

  // argv wins over the environment.
  const both = resolveIndexDirFromArgs(["--index", "/a"], { REPOHIVE_INDEX: "/b" }, cwd);
  assert.deepEqual(both, { ok: true, indexDir: "/a" });
});

test("resolveIndexDirFromArgs rejects bad invocations with specific messages", () => {
  const cwd = "/work";
  const none = resolveIndexDirFromArgs([], {}, cwd);
  assert.equal(none.ok, false);

  const dangling = resolveIndexDirFromArgs(["--index"], {}, cwd);
  assert.equal(dangling.ok, false);
  if (!dangling.ok) assert.match(dangling.message, /--index requires/);

  const unknown = resolveIndexDirFromArgs(["--frobnicate"], {}, cwd);
  assert.equal(unknown.ok, false);
  if (!unknown.ok) assert.match(unknown.message, /unknown option/);

  const extra = resolveIndexDirFromArgs(["/a", "/b"], {}, cwd);
  assert.equal(extra.ok, false);

  const conflicting = resolveIndexDirFromArgs(["--index", "/a", "/b"], {}, cwd);
  assert.equal(conflicting.ok, false);

  const help = resolveIndexDirFromArgs(["--help"], {}, cwd);
  assert.deepEqual(help, { ok: true, help: true });
});
